[package]
name = "syndica_interview"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
axum = "0.7.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower = "0.5.1"
